### ISSUE TITLE
Comparison to two other methods

### ISSUE THREAD

**Issue by surmann** [daveio/whisperpush-unregister#12]
Hallo,

what is the advantage of this method to unregister compared to:
https://whispersystems.org/textsecure/unregister/
and
https://github.com/ctso/WhisperPushUnregister/releases

Thanks for your answer!
Dirk

**Comment by martinstuecklschwaiger** [comment]
`whisperpush-unregister` is a script that runs on your local machine. It's great, if you don't trust the two other methods or want to modify the source. 

[ctso/WhisperPushUnregister](https://github.com/ctso/WhisperPushUnregister/releases) is an App that needs to be installed on your phone, so it only works if the phone did not get broken or resetted. 

If you just need a fast way to unregister, you better go with [whispersystems.org/textsecure/unregister](http://whispersystems.org/textsecure/unregister). (The reason the other two options exist, is mostly because [whispersystems.org/textsecure/unregister](http://whispersystems.org/textsecure/unregister) did not exist when they were created.

**Comment by surmann** [comment]
Thanks for your answer, that helps me a lot!
